# Generated by Django 5.0.2 on 2024-02-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0001_initial'),
        ('materiaprima', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='pedi_insumos',
            field=models.ManyToManyField(blank=True, to='insumos.implementostrabajo'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='pedi_materiaprima',
            field=models.ManyToManyField(blank=True, to='materiaprima.materiaprima'),
        ),
    ]
