<<<<<<< HEAD
# Generated by Django 5.0.2 on 2024-04-26 18:18

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 5.0.2 on 2024-05-04 22:56

import django.db.models.deletion
>>>>>>> a1149eb053fc25177279bf19269916628958bfa8
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        ('proveedores', '0001_initial'),
>>>>>>> a1149eb053fc25177279bf19269916628958bfa8
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
<<<<<<< HEAD
            name='pedi_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
=======
            name='pedi_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedores'),
>>>>>>> a1149eb053fc25177279bf19269916628958bfa8
        ),
    ]
