# Generated by Django 5.0.2 on 2024-04-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedidos_pedi_fecha_alter_pedidos_pedi_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
