# Generated by Django 5.0.2 on 2024-04-29 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_remove_pedidos_is_active_pedidos_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosaudit',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.pedidos'),
        ),
    ]
