# Generated by Django 5.0.2 on 2024-04-29 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_pedidosaudit_changed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosaudit',
            name='pedido',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='pedidos.pedidos'),
        ),
    ]
