# Generated by Django 5.0.2 on 2024-04-22 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsumosGenerico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='ImplementosTrabajo',
            fields=[
                ('it_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('it_cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('it_fechaEntrega', models.DateField(verbose_name='Fecha Entrega')),
                ('it_estado', models.CharField(choices=[('0', 'Disponible'), ('1', 'No Disponible')], max_length=1, verbose_name='Estado')),
                ('it_nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos.insumosgenerico')),
            ],
        ),
    ]
