# Generated by Django 5.0.2 on 2024-05-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0002_implementosaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementostrabajo',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
