# Generated by Django 5.0.2 on 2024-05-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0003_insumosgenerico_cantidad_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumosgenerico',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
