# Generated by Django 5.0.2 on 2024-05-22 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0003_implementostrabajo_deleted'),
        ('insumos', '0004_insumosgenerico_updated_at'),
    ]

    operations = [
    ]
