# Generated by Django 5.0.2 on 2024-04-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('num_factura', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Numero Factura')),
                ('fac_fechaLlegada', models.DateField(verbose_name='Fecha Llegada')),
                ('fac_numeroUnidades', models.PositiveIntegerField(verbose_name='Numero de Unidades')),
                ('fac_subtotal', models.FloatField(verbose_name='Subtotal')),
                ('fac_total', models.FloatField(default=0.0, verbose_name='Total')),
                ('img_factura', models.ImageField(blank=True, null=True, upload_to='facturas')),
            ],
        ),
        migrations.CreateModel(
            name='IVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0, verbose_name='IVA')),
            ],
        ),
    ]
