# Generated by Django 5.0.2 on 2024-04-26 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturas', '0001_initial'),
        ('pedidos', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='fac_numeroPedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedidos'),
        ),
        migrations.AddField(
            model_name='facturas',
            name='fac_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedores'),
        ),
        migrations.AddField(
            model_name='facturas',
            name='fac_iva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.iva'),
        ),
    ]
