# Generated by Django 5.0.2 on 2024-03-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturas',
            name='id',
        ),
        migrations.AlterField(
            model_name='facturas',
            name='num_factura',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Numero Factura'),
        ),
    ]
