# Generated by Django 5.0.2 on 2024-04-30 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_initial'),
        ('pedidos', '0007_alter_pedidosaudit_pedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturas',
            name='is_active',
        ),
        migrations.AddField(
            model_name='facturas',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FacturasAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('C', 'Creado'), ('U', 'Actualizado'), ('D', 'Borrado')], max_length=1)),
                ('details', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='pedido_logs', to='pedidos.pedidos')),
                ('proveedor', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='prov_logs', to='pedidos.pedidos')),
            ],
        ),
    ]
