# Generated by Django 5.0.2 on 2024-04-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='fac_total',
            field=models.FloatField(default=0.0, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='fac_subtotal',
            field=models.FloatField(verbose_name='Subtotal'),
        ),
    ]
