# Generated by Django 5.0.2 on 2024-04-30 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_remove_facturas_is_active_facturas_deleted_and_more'),
        ('proveedores', '0002_remove_proveedores_is_active_proveedores_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturasaudit',
            name='proveedor',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='prov_logs', to='proveedores.proveedores'),
        ),
    ]
