# Generated by Django 5.0.2 on 2024-04-22 21:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_facturas_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='fac_fechaLlegada',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Llegada'),
        ),
    ]
