# Generated by Django 5.0.2 on 2024-04-11 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_facturas_fac_total_alter_facturas_fac_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='IVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='IVA')),
            ],
        ),
        migrations.AlterField(
            model_name='facturas',
            name='fac_iva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.iva'),
        ),
    ]
