# Generated by Django 5.0.2 on 2024-04-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0004_iva_alter_facturas_fac_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iva',
            name='valor',
            field=models.FloatField(default=0, verbose_name='IVA'),
        ),
    ]
