# Generated by Django 5.0.2 on 2024-04-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
