# Generated by Django 5.0.2 on 2024-05-11 21:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
