# Generated by Django 5.0.2 on 2024-05-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_employee_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraudit',
            name='action',
            field=models.CharField(choices=[('C', 'Creado'), ('U', 'Actualizado'), ('D', 'Borrado'), ('L', 'Login'), ('O', 'Logout')], max_length=1),
        ),
    ]
