# Generated by Django 5.0.2 on 2024-05-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_useraudit_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraudit',
            name='action',
            field=models.CharField(choices=[('C', 'Creado'), ('U', 'Actualizado'), ('D', 'Borrado'), ('L', 'Inicio de Sesión'), ('O', 'Cerrado de Sesión')], max_length=1),
        ),
    ]
