# Generated by Django 5.0.2 on 2024-03-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiaprima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procesamiento',
            fields=[
                ('cod_procesamiento', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('proces_nombreProd', models.CharField(max_length=50, verbose_name='Nombre')),
                ('proces_pesoMpCruda', models.FloatField(verbose_name='Peso Crudo')),
                ('proces_pesoPostProceso', models.FloatField(verbose_name='Peso Post Proceso')),
                ('proces_merma', models.FloatField(verbose_name='Peso Merma')),
                ('proces_check', models.CharField(choices=[('0', 'Aprobado'), ('1', 'No Aprobado')], max_length=1, verbose_name='estado')),
                ('proces_materiaprima', models.ManyToManyField(blank=True, to='materiaprima.materiaprima')),
            ],
        ),
    ]
