# Generated by Django 5.0.2 on 2024-04-24 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiaprima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procesamiento',
            fields=[
                ('cod_procesamiento', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('proces_pesoMpCruda', models.FloatField(verbose_name='Peso Crudo')),
                ('proces_pesoPostProceso', models.FloatField(verbose_name='Peso Post Proceso')),
                ('proces_merma', models.FloatField(verbose_name='Peso Merma')),
                ('proces_check', models.CharField(choices=[('0', 'Aprobado'), ('1', 'No Aprobado')], max_length=1, verbose_name='estado')),
                ('proces_materiaprima', models.ManyToManyField(to='materiaprima.materiaprima')),
            ],
        ),
        migrations.CreateModel(
            name='Picado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pica_cantidad', models.IntegerField(default=100)),
                ('pica_check', models.CharField(choices=[('0', 'Aprobado'), ('1', 'No Aprobado')], max_length=1, verbose_name='estado')),
                ('cod_procesamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procesamiento.procesamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equi_encargadoCocina', models.CharField(max_length=50, verbose_name='Nombre')),
                ('equi_encargadoEntrega', models.CharField(max_length=50, verbose_name='Nombre')),
                ('equi_calidad', models.CharField(choices=[('0', 'Aprobado'), ('1', 'No Aprobado')], max_length=1, verbose_name='estado')),
                ('equi_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('equi_check', models.CharField(choices=[('0', 'Aprobado'), ('1', 'No Aprobado')], max_length=1, verbose_name='estado')),
                ('cod_procesamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procesamiento.procesamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Coccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocc_tiempoCoccion', models.IntegerField(default=100)),
                ('cocc_temperaturafinal', models.FloatField(verbose_name='temperatura final')),
                ('cocc_check', models.CharField(choices=[('0', 'Aprobado'), ('1', 'No Aprobado')], max_length=1, verbose_name='estado')),
                ('cod_procesamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procesamiento.procesamiento')),
            ],
        ),
    ]
