# Generated by Django 5.0.2 on 2024-04-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procesamiento',
            name='proces_check',
        ),
        migrations.RemoveField(
            model_name='procesamiento',
            name='proces_pesoMpCruda',
        ),
        migrations.AddField(
            model_name='picado',
            name='pica_merma',
            field=models.FloatField(default=0, verbose_name='Peso Merma'),
        ),
        migrations.AddField(
            model_name='picado',
            name='pica_nombre',
            field=models.CharField(default='NULL', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='picado',
            name='pica_pesoMPposproceso',
            field=models.FloatField(default=0, verbose_name='Peso'),
        ),
        migrations.AddField(
            model_name='procesamiento',
            name='proces_estado',
            field=models.CharField(choices=[('0', 'Aprobado'), ('1', 'No Aprobado')], default='0', max_length=1, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='procesamiento',
            name='proces_pesoMP',
            field=models.FloatField(default=0.0, verbose_name='Peso '),
        ),
        migrations.AlterField(
            model_name='coccion',
            name='cocc_check',
            field=models.CharField(choices=[('0', 'Aprobado'), ('1', 'No Aprobado')], default='0', max_length=1, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='coccion',
            name='cocc_tiempoCoccion',
            field=models.TimeField(default=100),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='equi_check',
            field=models.CharField(choices=[('0', 'Aprobado'), ('1', 'No Aprobado')], default='0', max_length=1, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='picado',
            name='pica_cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='picado',
            name='pica_check',
            field=models.CharField(choices=[('0', 'Aprobado'), ('1', 'No Aprobado')], default='0', max_length=1, verbose_name='estado'),
        ),
    ]
