# Generated by Django 5.0.2 on 2024-04-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coccion',
            name='id',
        ),
        migrations.AddField(
            model_name='coccion',
            name='cocc_cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='coccion',
            name='cocc_merma',
            field=models.FloatField(default=0, verbose_name='Peso Merma'),
        ),
        migrations.AddField(
            model_name='coccion',
            name='cocc_nombre',
            field=models.CharField(default='NULL', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='coccion',
            name='cocc_pesoMPposproceso',
            field=models.FloatField(default=0, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='coccion',
            name='cocc_check',
            field=models.CharField(choices=[('0', 'Aceptado'), ('1', 'Rechazado')], default='0', max_length=1, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='coccion',
            name='cod_procesamiento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='picado',
            name='cod_procesamiento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='picado',
            name='pica_check',
            field=models.CharField(choices=[('0', 'Aprobado'), ('1', 'No Aprobado')], max_length=1, verbose_name='estado'),
        ),
    ]
