# Generated by Django 5.0.2 on 2024-05-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaprima', '0002_initial'),
        ('procesamiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picado',
            name='pica_nombre',
        ),
        migrations.DeleteModel(
            name='Procesamiento',
        ),
        migrations.AddField(
            model_name='picado',
            name='pica_nombre',
            field=models.ManyToManyField(blank=True, to='materiaprima.materiaprima'),
        ),
    ]
