# Generated by Django 5.0.2 on 2024-03-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaprima', '0003_alter_desinfeccion_obsevacion'),
        ('procesamiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procesamiento',
            name='proces_nombreProd',
        ),
        migrations.AlterField(
            model_name='procesamiento',
            name='proces_materiaprima',
            field=models.ManyToManyField(to='materiaprima.materiaprima'),
        ),
    ]
