# Generated by Django 5.0.2 on 2024-04-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0002_remove_coccion_id_coccion_cocc_cantidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coccion',
            old_name='cod_procesamiento',
            new_name='id_coccion',
        ),
    ]
