# Generated by Django 5.0.2 on 2024-05-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0002_remove_picado_pica_nombre_delete_procesamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picado',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
