# Generated by Django 5.0.2 on 2024-05-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaprima', '0002_initial'),
        ('procesamiento', '0003_picado_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='coccion',
            name='cocc_nombre',
        ),
        migrations.AddField(
            model_name='coccion',
            name='cocc_nombre',
            field=models.ManyToManyField(blank=True, to='materiaprima.materiaprima'),
        ),
    ]
