# Generated by Django 5.0.2 on 2024-05-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0004_equipos_deleted_remove_coccion_cocc_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coccion',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
