# Generated by Django 5.0.2 on 2024-05-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0005_coccion_deleted'),
        ('productoterminado', '0004_remove_productoterminado_idcoccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coccion',
            name='cocc_nombre',
        ),
        migrations.RemoveField(
            model_name='coccion',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='picado',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='picado',
            name='pica_nombre',
        ),
        migrations.AddField(
            model_name='coccion',
            name='cocc_producto',
            field=models.ManyToManyField(blank=True, to='productoterminado.productoterminadogenerico'),
        ),
        migrations.AddField(
            model_name='picado',
            name='pica_producto',
            field=models.ManyToManyField(blank=True, to='productoterminado.productoterminadogenerico'),
        ),
    ]
