# Generated by Django 5.0.2 on 2024-05-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaprima', '0004_materiaprimagenerica_cantidad_total_and_more'),
        ('procesamiento', '0006_remove_coccion_cocc_nombre_remove_coccion_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coccion',
            name='cocc_producto',
        ),
        migrations.RemoveField(
            model_name='equipos',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='picado',
            name='pica_producto',
        ),
        migrations.AddField(
            model_name='coccion',
            name='cocc_nombre',
            field=models.CharField(default='NULL', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='picado',
            name='pica_nombre',
            field=models.CharField(default='NULL', max_length=50, verbose_name='Nombre'),
        ),
        migrations.CreateModel(
            name='Procesamiento',
            fields=[
                ('cod_procesamiento', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('proces_pesoMP', models.FloatField(default=0.0, verbose_name='Peso ')),
                ('proces_pesoPostProceso', models.FloatField(verbose_name='Peso Post Proceso')),
                ('proces_merma', models.FloatField(verbose_name='Peso Merma')),
                ('proces_estado', models.CharField(choices=[('0', 'Aprobado'), ('1', 'No Aprobado')], default='0', max_length=1, verbose_name='estado')),
                ('proces_materiaprima', models.ManyToManyField(to='materiaprima.materiaprima')),
            ],
        ),
    ]
