<<<<<<< HEAD
# Generated by Django 5.0.2 on 2024-04-26 18:18
=======
# Generated by Django 5.0.2 on 2024-05-04 22:56
>>>>>>> a1149eb053fc25177279bf19269916628958bfa8

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExistenciaMp',
            fields=[
                ('codigo', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Código')),
                ('cantidadIngresada', models.PositiveIntegerField(verbose_name='Cantidad Ingresada')),
                ('cantidadEgresada', models.PositiveIntegerField(verbose_name='Cantidad Egresada')),
            ],
        ),
    ]
