# Generated by Django 5.0.2 on 2024-05-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('existencias', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='existenciamp',
            old_name='cantidadIngresada',
            new_name='cantidadDisponible',
        ),
    ]
