# Generated by Django 5.0.2 on 2024-05-21 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('existencias', '0008_rename_existenciamp_existenciamateriaprima_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExistenciasImplementosTrabajo',
        ),
    ]
