# Generated by Django 5.0.2 on 2024-05-21 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('existencias', '0009_delete_existenciasimplementostrabajo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExistenciaMateriaPrima',
        ),
    ]
