# Generated by Django 5.0.2 on 2024-05-23 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('existencias', '0011_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExistenciaMp',
        ),
    ]
