# Generated by Django 5.0.2 on 2024-04-22 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesinfectanteGenerico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('mp_lote', models.IntegerField(primary_key=True, serialize=False, verbose_name='Lote')),
                ('mp_cantidad', models.IntegerField(default=100)),
                ('mp_fechallegada', models.DateField(verbose_name='Fecha Ingreso')),
                ('mp_fechavencimiento', models.DateField(verbose_name='Fecha Vencimiento')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaPrimaGenerica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('mp_tipo', models.CharField(choices=[('0', 'Proteina'), ('1', 'Lácteo'), ('2', 'Verduras'), ('3', 'Frutas'), ('4', 'Otros')], default=0, max_length=1, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Desinfeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentracion', models.IntegerField(verbose_name='Concentración')),
                ('tiempo_inicio', models.TimeField(verbose_name='Tiempo de Inicio')),
                ('tiempo_fin', models.TimeField(verbose_name='Fin Desinfección')),
                ('obsevacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('des_nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiaprima.desinfectantegenerico')),
                ('mp_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiaprima.materiaprima')),
            ],
        ),
        migrations.CreateModel(
            name='CaracteristicasOrganolepticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olor', models.BooleanField(default=False, verbose_name='Olor')),
                ('textura', models.BooleanField(default=False, verbose_name='Textura')),
                ('limpieza', models.BooleanField(default=False, verbose_name='Limpieza')),
                ('empaque', models.BooleanField(default=False, verbose_name='Empaque')),
                ('color', models.BooleanField(default=False, verbose_name='Color')),
                ('estado', models.CharField(choices=[('0', 'Aprobado'), ('1', 'No Aprobado')], max_length=1, verbose_name='Estado')),
                ('mp_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiaprima.materiaprima')),
            ],
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='mp_nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiaprima.materiaprimagenerica'),
        ),
    ]
