# Generated by Django 5.0.2 on 2024-03-08 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaprima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Existenciamp',
            fields=[
                ('exiMP_codigo', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='codigo')),
                ('exiMP_cantidadIngresada', models.PositiveBigIntegerField(verbose_name='cantidad ingresada')),
                ('exiMP_cantidadEgresada', models.PositiveBigIntegerField(verbose_name='cantidad de salida')),
                ('mp_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiaprima.materiaprima')),
            ],
        ),
    ]
