# Generated by Django 5.0.2 on 2024-02-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaprima', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='cantidad',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='tipo',
            field=models.CharField(choices=[('0', 'Proteina'), ('1', 'Lácteo'), ('2', 'Verduras'), ('3', 'Frutas')], default=0, max_length=1, verbose_name='Tipo'),
        ),
    ]
