# Generated by Django 5.0.2 on 2024-02-14 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiaprima', '0002_materiaprima_cantidad_materiaprima_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materiaprima',
            old_name='cantidad',
            new_name='mp_cantidad',
        ),
        migrations.RenameField(
            model_name='materiaprima',
            old_name='tipo',
            new_name='mp_tipo',
        ),
    ]
