# Generated by Django 5.0.2 on 2024-03-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaprima', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desinfeccion',
            name='obsevacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones'),
        ),
    ]
