# Generated by Django 5.0.2 on 2024-04-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaprima', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiaprima',
            name='mp_tipo',
        ),
        migrations.AddField(
            model_name='materiaprimagenerica',
            name='mp_tipo',
            field=models.CharField(choices=[('0', 'Proteina'), ('1', 'Lácteo'), ('2', 'Verduras'), ('3', 'Frutas')], default=0, max_length=1, verbose_name='Tipo'),
        ),
    ]
