# Generated by Django 5.0.2 on 2024-04-25 20:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaprima', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='mp_fechallegada',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Ingreso'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='mp_fechavencimiento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Vencimiento'),
        ),
    ]
