# Generated by Django 5.0.2 on 2024-04-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaprima', '0003_remove_materiaprima_mp_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprimagenerica',
            name='mp_tipo',
            field=models.CharField(choices=[('0', 'Proteina'), ('1', 'Lácteo'), ('2', 'Verduras'), ('3', 'Frutas'), ('4', 'Otros')], default=0, max_length=1, verbose_name='Tipo'),
        ),
    ]
