# Generated by Django 5.0.2 on 2024-05-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaprima', '0003_materiaprimaaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprimagenerica',
            name='cantidad_total',
            field=models.IntegerField(default=0, verbose_name='Cantidad Total'),
        ),
        migrations.AddField(
            model_name='materiaprimagenerica',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
