# Generated by Django 5.0.2 on 2024-04-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiaprima', '0004_alter_materiaprimagenerica_mp_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Existenciamp',
        ),
    ]
