# Generated by Django 5.0.2 on 2024-03-18 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procesamiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoTerminado',
            fields=[
                ('PT_lote', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('PT_prodNombre', models.CharField(max_length=50, verbose_name='Nombre Producto Terminado')),
                ('PT_fechapreparacion', models.DateField(verbose_name='Fecha Preparacion')),
                ('PT_fechavencimiento', models.DateField(verbose_name='Fecha Vencimiento')),
                ('IdCoccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procesamiento.coccion')),
                ('IdPicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procesamiento.picado')),
            ],
        ),
        migrations.CreateModel(
            name='ExistenciaPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExisPT_CantidadIngresada', models.IntegerField(verbose_name='Cantidad Ingresada')),
                ('ExisPT_CantidadEgresada', models.IntegerField(verbose_name='Cantidad Egresada')),
                ('PT_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productoterminado.productoterminado')),
            ],
        ),
        migrations.CreateModel(
            name='EmpaqueProductoTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_pesoKgPT', models.FloatField(verbose_name='Peso Empaque')),
                ('Emp_cantidadBolsas', models.IntegerField(verbose_name='Cantidad Bolsas')),
                ('PT_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productoterminado.productoterminado')),
            ],
        ),
        migrations.CreateModel(
            name='CaracteristicasOrganolepticasPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(max_length=50, verbose_name='Observaciones')),
                ('olor', models.BooleanField(default=False, verbose_name='Olor')),
                ('sabor', models.BooleanField(default=False, verbose_name='Sabor')),
                ('textura', models.BooleanField(default=False, verbose_name='Textura')),
                ('color', models.BooleanField(default=False, verbose_name='Color')),
                ('estado', models.CharField(choices=[('0', 'Aprobado'), ('1', 'No Aprobado')], max_length=1, verbose_name='Estado')),
                ('PT_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productoterminado.productoterminado')),
            ],
        ),
        migrations.CreateModel(
            name='Vacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad_bolsas_rechazadas', models.IntegerField(verbose_name='Cantidad Bolsas Rechazadas')),
                ('Cantidad_bolsas_liberadas', models.IntegerField(verbose_name='Cantidad Bolsas Liberadas')),
                ('PT_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productoterminado.productoterminado')),
            ],
        ),
    ]
