# Generated by Django 5.0.2 on 2024-04-15 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0001_initial'),
        ('productoterminado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoterminado',
            name='idCoccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procesamiento.coccion'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='idPicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procesamiento.picado'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='pt_cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='pt_lote',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
