# Generated by Django 5.0.2 on 2024-05-08 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productoterminado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoTerminadoAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('C', 'Creado'), ('U', 'Actualizado'), ('D', 'Borrado')], max_length=1)),
                ('details', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('ProductoTerminado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='productoterminado.productoterminado')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productoterminado.productoterminado')),
            ],
        ),
    ]
