# Generated by Django 5.0.2 on 2024-05-10 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productoterminado', '0002_productoterminadoaudit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoterminadoaudit',
            old_name='ProductoTerminado',
            new_name='productoterminado',
        ),
    ]
